### ISSUE TITLE
Property line is invalid

### ISSUE THREAD

**Issue by pinpox** [stevearc/vim-arduino#1]
I get this error when trying to copile/upload.

The quotes look strange (' and ")

![2016-05-09-170807_1248x260_scrot](https://cloud.githubusercontent.com/assets/1719781/15117800/8299ad2a-1609-11e6-8749-10e69082a34d.png)

**Comment by stevearc** [comment]
Hi binary,

What do you get when you do a `:echo g:arduino_programmer`? It should say `arduino:usbtinyisp`.

Assuming that looks normal, you can add this to `vim-arduino/autoload/arduino.vim` on line 264:
```
exe ":silent !echo " . cmd
```
This will print out the full command that it's running, which should give you some clues.

**Comment by binaryplease** [comment]
Thanks!

The :echo g:arduino_programmer looks normal.

I added "exe ":silent !echo " . cmd" as you recommended, but the messages are cleared to fast to see the output properly. If I saw it right, the error is the same though.

**Comment by stevearc** [comment]
With that line you're not looking for the error, you're looking for the line that's actually running the `arduino` command, so you can check the args and run it manually if need be. It will be in your terminal history if you just scroll up, or quit vim and scroll up. If you want it to stop immediately on printing you can remove the `silent`
