### ISSUE TITLE
:ArduinoSerial command does not work

### ISSUE THREAD

**Issue by coldspark29** [stevearc/vim-arduino#27]
I just get the message

```
executing job failed: File or directory not found
```

**Comment by stevearc** [comment]
You have to have `screen` installed to use `ArduinoSerial`. Or you can install some other program that can handle serial port communication like `picocom` and set `let g:arduino_serial_cmd = 'picocom {port} -b {baud} -l'`

What version of vim are you using? This message is vim saying that it can't find the command (likely `screen`), but if I try it without screen installed I see `/bin/bash: screen: command not found`
