### ISSUE TITLE
Does not work in folders with spaces in their names

### ISSUE THREAD

**Issue by madskjeldgaard** [stevearc/vim-arduino#30]
Hi !

@salkin-mada and I found a small error. If the arduino sketch folder has a space in it's name, like `blinky sketch`, vim-arduino does not recognise it (but ARDUINO IDE does is able to verify the same sketch) and spits out the error:

```
Picked up JAVA_TOOL_OPTIONS:
Error: Must specify exactly one sketch file

[Process exited 3]
```
Removing the space from the name makes it work again :) 
best regards

PS. The computer used for testing is an Arch Linux installation ,NVIM version 0.4.4, arduino 1.8.13, teensy 1.5.3. 

Thanks!

**Comment by stevearc** [comment]
Thanks for the report! As expected, it was an argument escaping issue. Should be fixed now!
