### ISSUE TITLE
Compilation fails when using multiple source files

### ISSUE THREAD

**Issue by darksworm** [stevearc/vim-arduino#31]
**User story:** When writing more complicated arduino sketches, I want to split the code up into multiple files.

**Issue**: Currently if I try to use `include` to inclue another source file, the compilation fails.

**How to recreate**

Create two files in the same directory:
```cpp
// test.c.ino
#include "test.h"

void setup() {}
void loop() {}
```

```cpp
// test.h
// this file is empty
```

Try to compile & upload the sketch and this error will appear:
```
test.c:1:10: fatal error: test.h: No such file or directory
 19  #include "test.h"
 20     ┆   ┆ ^~~~~~~~
 21 compilation terminated.
 22 exit status 1
```

This code, however, compiles and uploads successfully when using the arduino-ide.

**Comment by darksworm** [comment]
Upon some further inspection this seems to be an issue with the arduino upload command.

```bash
arduino --upload --board arduino:avr:uno --port /dev/ttyUSB0 --pref programmer=arduino:avrispmkii --pref build.path=./build test.ino
```
results in the same error, where as this works (after changing `test.h` to `test.cpp`):
```bash
arduino-cli compile -b arduino:avr:uno . -v --build-path `pwd`/build && arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:uno
```

**Comment by darksworm** [comment]
Some time later... I don't know what I did, but it suddenly started working...

**Comment by darksworm** [comment]
It has been worked flawlessly ever since. It was probably a peculiarity with my system.

**Comment by stevearc** [comment]
Glad to hear it's working! LMK if you ever manage to repro

**Comment by darksworm** [comment]
Just managed to reproduce it - the issue occurs when the main `ino` file is in a directory that is named differently than it.

In my case - my main source file is named `wul.ino`, so it expects that it's parent directory is called `wul`.

See attached gifs for reproduction steps & proof:
![wul-src](https://user-images.githubusercontent.com/9987548/96163843-137a8280-0f23-11eb-8927-d921dcb24fef.gif)
compiling `wul.ino` from a directory named `src` - does not work.

![wul-wul](https://user-images.githubusercontent.com/9987548/96163892-21c89e80-0f23-11eb-9a97-0117f943c522.gif)
compiling `wul.ino` from a directory named `wul` - works.

I'm sure that this issue is isolated to the directory naming, but just in case, the source code I'm trying to compile is availlable [here](https://github.com/darksworm/wake-up-light/tree/ae3137ec975296fba46982e92c3ad11f03d2bfe6).

**Comment by stevearc** [comment]
Unfortunately this seems to be a limitation of the Arduino toolchain. There has been some discussion and it's possible that this requirement will be lifted in the future https://github.com/arduino/arduino-cli/issues/948

**Comment by grammoboy2** [comment]
I can only use one tab in nvim ifor Arduino it seems indeed. When I open another tab with a other file to edit, it still tries to compile the first file, even when I've closed that file.

**Comment by stevearc** [comment]
Looks like the arduino-cli enhancement was declined. Seems like this is just the way Arduino works for the foreseeable future.
