### ISSUE TITLE
Not working with vim under Ubuntu 18.04

### ISSUE THREAD

**Issue by Eric97** [stevearc/vim-arduino#33]
After installing the plugin with `plug`, all the arduino commands cannot be invoked either in Vim or NeoVim. The default `arduino_cmd` is installed at `/usr/local/bin/arduino`.

**Comment by stevearc** [comment]
When you say "cannot be invoked", what is actually happening? And please post the output of `:ArduinoInfo` if you can.

**Comment by Eric97** [comment]
`:ArduinoInfo` and the other `:Ardu*` commands are not recognized as valid editor commands. 
`:help arduino` can display the help document though.

**Comment by stevearc** [comment]
Ah, the commands are defined in the ftplugin file https://github.com/stevearc/vim-arduino/blob/master/ftplugin/arduino.vim

It's possible that the files you're editing aren't properly recognized. The ftdetect rules live here: https://github.com/stevearc/vim-arduino/blob/master/ftdetect/arduino.vim

Try doing a `:se ft?` to check the detected filetype. If it's not set to `arduino` then that would explain it, and then we can figure out why the detection isn't working.

**Comment by Eric97** [comment]
Thanks. After opening the `.ino` file in vim, then the commands can work with the correct file type detected!
