### ISSUE TITLE
ArduinoChoosePort Broken

### ISSUE THREAD

**Issue by jonascant** [stevearc/vim-arduino#38]
https://github.com/stevearc/vim-arduino/blob/38bdd8396231f74df843ce88702550aae5bcfb32/autoload/arduino.vim#L692-L696
This code modification broke my ArduinoChoosePort.
I get an error message that "' '.(i+1).') '.v.label " is not found in Dictionary (i had to translate from german, might not be accurate)

Reverting the code to

`let labels = s:ConvertItemsToLabels(items)
call map(labels, {i, l ->
\ i < 9
\ ? ' '.(i+1).') '.l
\ : (i+1).') '.l`

Made it work again.

**Comment by stevearc** [comment]
Thanks for the report! Should be fixed now
