### ISSUE TITLE
Not working with Ubuntu 20.04, fails in `chooser.vim`

### ISSUE THREAD

**Issue by wannabecoffeenerd** [stevearc/vim-arduino#42]
Hi, I'm using the default vim package on ubuntu 20.04 (vim version 8.1.2269) and added `vim-arduino` using `vim-plug`. I have the `arduino-cli` in my path and am able to list the boards I have, etc. But when I do `:ArduinoChooseBoard`, I run into a bunch of errors:
```
Error detected while processing /home/----/.vim/plugged/vim-arduino/autoload/arduino/chooser.vim:
line  107:
E117: Unknown function: luaeval
Error detected while processing function arduino#ChooseBoard[6]..arduino#chooser#Choose:
line   11:
E121: Undefined variable: g:arduino_telescope_enabled
```
Are there any dependencies I'm missing or do I need to do something else to get this working?

**Comment by stevearc** [comment]
Thanks for the PR! This error was because I was using a function present in Neovim that is not present in Vim 8. Should be fixed now if you update to the latest master.
