### ISSUE TITLE
How to stop Serial Monitor

### ISSUE THREAD

**Issue by saschahoeche** [stevearc/vim-arduino#44]
While the plugin works really great, i don't know how to stop/close the serial monitor after opening it and reading the serial stream.
Any pointers?

**Comment by stevearc** [comment]
If you're using `screen` (the default, see `:h arduino_serial_cmd`) would think that ctrl+c should stop it. Is that not working for you?

**Comment by saschahoeche** [comment]
I use the :ArduinoUploadAndSerial command or the :ArduinoSerial command. But Ctrl+C doesn't work on either. I am sure the fault is on my side but i can't seem to figure it out.

**Comment by stevearc** [comment]
Ah, of course it's screen so you have to kill the screen session using it's escape key. By default this is bound to `<C-a><C-k>`

**Comment by saschahoeche** [comment]
Cheers, that worked
