### ISSUE TITLE
:ArduinoChoose* commands do not work in Vim9

### ISSUE THREAD

**Issue by ubaldot** [stevearc/vim-arduino#56]
**Describe the bug**
Commands such as `:ArduinoChooseBoard, :ArduinoChoosePort` and `:ArduinoChooseProgrammer`, don't seem to work in Vim9, see screenshots below.

**System information**
- OS: Mac Os X 13.4
- Vim: 9.0.1276
- CLI version: arduino-cli  Version: 0.33.0 Commit: ca60d4b4 Date: 2023-05-29T15:18:18Z
- ArduinoInfo: 
- 
```
Board         : arduino:avr:uno
Programmer    : 
Port          : /dev/tty.usbmodem101
Baud rate     : 9600
Hardware dirs : /Users/ubaldot/Library/Arduino15/packages/arduino/hardware/avr/1.8.6
Verify command: arduino-cli compile -b arduino:avr:uno -p /dev/tty.usbmodem101 --build-path "/Users/ubaldot/Documents/arduino/build" -v "/Users/ubaldot/Documents/arduino/pippo.ino"
```

**To Reproduce**
Install MacVim 9.0.1276, open a .ino file and run any vim-arduino command.

**Expected behavior**
I can operate with my arduino uno board. 

**Screenshots**
<img width="1320" alt="image" src="https://github.com/stevearc/vim-arduino/assets/10845685/89ca675f-d9b3-4289-b34f-88028acb9bf1">

**Additional context**
Congrats for the plugin! Starred! :)

**Comment by stevearc** [comment]
I believe it should be fixed. Can you give it another try?

**Comment by ubaldot** [comment]
Yes, now it does. :) Thanks!
