### ISSUE TITLE
Run SerialMonitor in another tmux pane

### ISSUE THREAD

**Issue by vlappa** [stevearc/vim-arduino#58]
I'm using vim-arduino with vim-slime in tmux. Currently the SerialMonitor opens in the same tmux pane as the logging output for uploading. I think one has to close the SerialMonitor to run ArduinoUploadAndSerial again.

Would it be possible to have a third tmux pane open, where the SerialMonitor is running constantly, while one can still Upload to the Arduino and check the logs?

**Comment by stevearc** [comment]
I believe that vim-slime only supports sending text to a single target. The [public API](https://github.com/jpalardy/vim-slime/blob/7cfe5ac9f5d5512a7aeeb2e0a13a64975ac129e5/autoload/slime.vim#L525) only accepts `text` as an argument; there's no way to target it to a specific panel. You might have to just open a manual pane for the serial command
